plugins { id 'com.android.application' }

android {
    namespace 'com.nastx.nousdeux'
    compileSdk 36

    defaultConfig {
        applicationId 'com.nastx.nousdeux.live'
        minSdk 26
        targetSdk 36
        versionCode 5
        versionName '1.1.3'
    }

    signingConfigs {
        devStable {
            storeFile file('nous-deux-dev.keystore')
            storePassword 'nousdeux-dev-2026'
            keyAlias 'nousdeux-dev'
            keyPassword 'nousdeux-dev-2026'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.devStable
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.devStable
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
